### ISSUE TITLE
Badly configured systemd on Opensuse docker images leads to crashes/issues on local machine.

### ISSUE THREAD

**Issue by Zialus** [mesaguy/ansible-molecule#1]
You can follow the discussion here for more details: https://github.com/jam82/buildah-molecule-images/issues/3

The basic gist of it is that: there are some systemd related files that need to be deleted, or else, running the OpenSUSE containers can lead to systemd on the local machine being taken over by systemd of the docker container.

**Comment by mesaguy** [comment]
Please feel free to create a pull request or provide more details
